apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-godaddy
  namespace: externaldns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      namespace: externaldns
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.11.0
          args:
          - --source=service
          - --source=ingress
          - --domain-filter=in10minutes.dev
          - --provider=godaddy
          - --txt-prefix=external-dns.
          - --txt-owner-id=owner-id
          - --godaddy-api-key=$(GODADDY_API_KEY)
          - --godaddy-api-secret=$(GODADDY_API_SECRET)
          env:
            - name: GODADDY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: GODADDY_API_KEY
            - name: GODADDY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: GODADDY_API_SECRET
